name: Daily Curl Command

on:
  schedule:
    - cron: '0 22 * * *'  # 每天UTC时间6点运行
  workflow_dispatch:

jobs:
  curl-job:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu虚拟环境
    steps:
      - name: Run curl
        run: |
          curl 'https://api1.zhtec.xyz/api/user/checkin?turnstile=&captchaId=&captcha='   -X 'POST'   -H 'authority: api1.zhtec.xyz'   -H 'accept: application/json, text/plain, */*'   -H 'accept-language: zh-CN,zh;q=0.9'   -H 'content-length: 0'   -H 'cookie: session=MTcwOTY5OTU1OXxEWDhFQVFMX2dBQUJFQUVRQUFEX29mLUFBQVVHYzNSeWFXNW5EQW9BQ0hWelpYSnVZVzFsQm5OMGNtbHVad3dOQUF0bmFYUm9kV0pmTlRFNU9RWnpkSEpwYm1jTUJnQUVjbTlzWlFOcGJuUUVBZ0FDQm5OMGNtbHVad3dJQUFaemRHRjBkWE1EYVc1MEJBSUFBZ1p6ZEhKcGJtY01EUUFMYjJGMWRHaGZjM1JoZEdVR2MzUnlhVzVuREE0QURGbG9iREJuWVU1NWREbFpad1p6ZEhKcGJtY01CQUFDYVdRRGFXNTBCQVFBX2lpZXwppVlTX71cOiMZqq0y7kRptXAjJ2PUE-n5cK5onoO00g==; cf_clearance=KCAnJ0mb3ceJuB1X8IaMX0_Jt.lsKoN6GJPpI95SnQk-1709700906-1.0.1.1-VOMTy6kbqHPxDun1bBQ6KdN8Fx5gcvC7qqN.LAjUvXH_B5spJQWg1qXc1TVrPyc1BNKNZyNKt98pUv3KDGH6jw'   -H 'origin: https://api1.zhtec.xyz'   -H 'referer: https://api1.zhtec.xyz/'   -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"'   -H 'sec-ch-ua-mobile: ?0'   -H 'sec-ch-ua-platform: "Linux"'   -H 'sec-fetch-dest: empty'   -H 'sec-fetch-mode: cors'   -H 'sec-fetch-site: same-origin'   -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'   --compressed
          
